services:
  backend:
    build:
      context: ./backend
    container_name: cephalon-onni-backend
    restart: unless-stopped
    ports:
      - "8000:8000" # keep for dev; can remove in prod
    depends_on:
      - mongodb
      - redis
    environment:
      # Mongo
      MONGO_URL: mongodb://cephalon-onni-mongo:27017

      # Graph is now Postgres (Apache AGE)
      GRAPH_DB_TYPE: postgres_age

      # Redis
      REDIS_URL: redis://redis:6379
    command: ["python", "-u", "app/main.py"]
    tty: true
    stdin_open: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cephalon-onni-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:7
    container_name: cephalon-onni-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:7-alpine
    container_name: cephalon-onni-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  mongodata:
  redisdata:
