services:
  backend:
    build: .
    container_name: cephalon-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017
      GRAPH_DB_TYPE: mongodb
    command: ["python", "app/main.py"]

  mongodb:
    image: mongo:7
    container_name: cephalon-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
